---
deployment:
  tasks:
    - export DEPLOYPATH=/home/siaeesco/ideas.siaees.com
    - /bin/rsync -av --exclude=".env" --exclude="storage/" --delete . $DEPLOYPATH
    - cd $DEPLOYPATH
    - if [ ! -f "$DEPLOYPATH/.env" ]; then cp $DEPLOYPATH/.env.example $DEPLOYPATH/.env; fi
    - php artisan key:generate
    - /opt/cpanel/composer/bin/composer install --optimize-autoloader --no-dev
    - chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
    - chown -R $USER:$USER $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache